### ISSUE TITLE
mình thấy module để dùng cho egov nhưng đưa lên không được

### ISSUE THREAD

**Issue by lyhuutrong** [hoaquynhtim99/accommodation#2]
chào bác. bác có thể cho mình hỏi là module này thấy bác có thể trong store là dùng được trong egov nhưng mình đưa lên thì nó báo lỗi tùm lum ấy bác. hichic. mong bác xem lại với ạ.

**Comment by hoaquynhtim99** [comment]
Bạn vui lòng mô tả rõ lỗi tùm lum là lỗi như thế nào nhé ?

**Comment by lyhuutrong** [comment]
module nhà trọ này dùng cho egov 1.1 được hã bác? với bác cho mình hỏi là 2 loại trong phần tải về trong store đó ạ. tải cái đầu hay cái thứ 2 để dùng trong egov ạ. với bác cho mình hỏi là mình tải về thì nó chỉ có admin default với default thôi ạ. nếu đổi thì đổi tên thế nào ạ.

**Comment by hoaquynhtim99** [comment]
Bạn xem số phiên bản của cái tải về và tương thích phiên bản, cái nào cao hơn thì xài.
Còn giao diện NukeViet default sẽ xài cho tất cả các giao diện khác được. vấn đề này bạn nên tìm hiểu hơn về nukeviet

Đổi tên giao diện thế nào bạn tham khảo tài liệu lập trình, ở đây mình không trả lời thêm về vấn đề này 

https://wiki.nukeviet.vn/programming4:theme
https://wiki.nukeviet.vn/nukeviet4:concepts:theme
